import json
import os
import argparse
import math
from collections import Counter
import time

# Optional: Gemini for LLM-as-Judge
try:
    import google.generativeai as genai
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False

def calculate_entropy(text):
    if not text: return 0
    counts = Counter(text)
    total = len(text)
    entropy = -sum((count/total) * math.log2(count/total) for count in counts.values())
    return entropy

def calculate_repetition(text, n=3):
    """Calculate the ratio of repeated n-grams."""
    words = text.split()
    if len(words) < n: return 0
    ngrams = [tuple(words[i:i+n]) for i in range(len(words)-n+1)]
    unique_ngrams = set(ngrams)
    return 1.0 - (len(unique_ngrams) / len(ngrams))

def judge_with_llm(text, prompt, api_key):
    if not HAS_GEMINI or not api_key:
        return None
    
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel('gemini-1.5-flash')
    
    judge_prompt = f"""
Evaluate the coherence of the following short story generated by a tiny language model.
Prompt: {prompt}
Generated Text: {text}

Rate from 1 to 5 for each category:
1. Grammar (1: Unreadable, 5: Perfect)
2. Coherence (1: Random words, 5: Logical flow)
3. Relevance (1: Irrelevant to prompt, 5: Matches prompt)

Return ONLY a JSON object like this:
{{"grammar": 3, "coherence": 2, "relevance": 4}}
"""
    try:
        response = model.generate_content(judge_prompt)
        res_text = response.text.strip()
        # Extract JSON from potential markdown blocks
        if "```json" in res_text:
            res_text = res_text.split("```json")[1].split("```")[0].strip()
        return json.loads(res_text)
    except Exception as e:
        print(f"Error judging with LLM: {e}")
        return None

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=str, default='results/generated_samples.json')
    parser.add_argument('--output', type=str, default='results/evaluation_results.json')
    parser.add_argument('--api_key', type=str, help='Gemini API Key for judge')
    parser.add_argument('--limit', type=int, default=5, help='Limit many samples per scale to judge (to save API credits)')
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Input file {args.input} not found.")
        return

    with open(args.input, 'r', encoding='utf-8') as f:
        samples = json.load(f)

    results = []
    scale_stats = {}

    print(f"Starting evaluation of {len(samples)} samples...")
    for idx, sample in enumerate(samples):
        scale = sample['scale']
        text = sample['text']
        prompt = sample['prompt']
        
        # 1. Auto Metrics
        entropy = calculate_entropy(text)
        repetition = calculate_repetition(text)
        
        # 2. LLM Judge (sampled)
        judge_scores = None
        # Only judge first N samples of each scale to save cost
        scale_count = scale_stats.get(scale, 0)
        if scale_count < args.limit and args.api_key:
            print(f"  Judging {scale} sample {scale_count+1}/{args.limit}...")
            judge_scores = judge_with_llm(text, prompt, args.api_key)
            scale_stats[scale] = scale_count + 1
            time.sleep(1) # Rate limit safety
            
        results.append({
            **sample,
            "entropy": entropy,
            "repetition_ratio": repetition,
            "judge_scores": judge_scores
        })

    with open(args.output, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"Evaluation complete. Saved to {args.output}")

if __name__ == "__main__":
    main()
